separating frr

diff --git a/p3/router/Makefile b/p3/router/Makefile
--- a/p3/router/Makefile
+++ b/p3/router/Makefile
@@ -8,6 +8,14 @@ NAME	?= Dockerfile
 
 build:
 	for i in $$(seq 1 $(COUNT)); do \
-		docker build -f $(NAME) -t $(IMAGE)-$$i .; \
+		test -f config/frr/R$$i.conf || { \
+			echo "ERROR: needs config/frr/R$$i.conf"; \
+			exit 1; \
+		}; \
+		docker build \
+			-f $(NAME) \
+			--build-arg ROUTER_ID=$$i \
+			-t $(IMAGE)-$$i \
+			. ; \
 	done
 
